language: objective-c
gemfile: Gemfile
before_script: 
- Scripts/before.sh
- Scripts/add-key.sh
after_script: 
- Scripts/remove-key.sh
after_success: 
- Scripts/testflight.sh
script: Scripts/build.sh
env: 
  global: 
  - APPNAME="xebia-ios"
  - "DEVELOPER_NAME=\"iPhone Developer: Alexis Kinsella (46N4T2UZ32)\""
  - PROFILE_UUID=E326D2CF-B8FE-4410-B9CC-CF569D60C47D
  - secure: cC8bGOtZ0kNbxHKJfqeWpLcgXpG/FbPB0JM9qdGY77HgUeM95YUk3QOfjagE27UBxGyem9JZ/TEaD2wzwmnxYCIAFTxp4XAPAPD/2xjlBh1EV8UTWDwmdzBa4biG5wVRdDUuAIMMZwHMH5VnG775w5wuA0gaTVsXAmMFUxEIheA=
  - secure: VtFd/HsLyDt1x/985MokRmPtdpjE+POhlhxGjSVAAg//VZUz+wz/GvtEcMQOsyI8O06+YAd8B2yRlPJDmcReO/S7E1Fh4ShqAp0oYHzlYHXHfcd/rK7DzzmIyrusrzHKMJo+yaD25+lUbkc196eoTW38SOmAwVCdlFr8jnMy96Q=
  - secure: KgS2HHz8j5782sidA0qADHt0IhLS5heW/8w61VLkgt41C5EtAXChlOr54emfkK7iwlrvIOzJhcdjWo5+5B8/XObkjbK+AmcSBoHsqAWC4XwvbA9uU/zcYJxb/76SVlpcCvnyMbJWBmHN9de2+T4ZzU9hngTOHWw17g4/5H5+t1I=
