language: objective-c
#rvm: 
# - 1.9.3
#gemfile: Gemfile
before_script: 
- Scripts/before_script.sh
- sudo easy_install cpp-coveralls
- sudo easy_install PyYAML
after_script: 
- Scripts/after_script.sh
after_success: 
- Scripts/testflight.sh
- ./Scripts/coveralls.rb --extension m --exclude-folder Artwork --exclude-folder bin --exclude-folder build --exclude-folder output --exclude-folder Pods --exclude-folder Resources --exclude-folder Scripts --exclude-folder Targets --exclude-folder Tests --exclude-folder Library/Tests
script: Scripts/build.sh
env: 
  global: 
  - LC_ALL="en_US.UTF-8"
  - APPNAME="Xebia"
  - "DEVELOPER_NAME=\"iPhone Developer: Alexis Kinsella (46N4T2UZ32)\""
  - PROFILE_UUID="978D2EE1-E2B3-43D8-9102-DD267A425BBE"
  - secure: AKohm7ovaPAkQ21iPe9eIChvrLKcFt1DdAfyzjpe9Pb8nudDsMOzI85QHTd4FWALA/YZ+VMQgPo3AjQy4BBMzx6nRIkA2lwldqDSaLAmcR9B9W91t/RghZs02SBxSPUp5lPkf4XkCEEsXiTPKLL/96nOnDPAx0nTL9A6LzxESLo=
  - secure: KUeVQN5BWMmDGX5HvxREMMbyz0+IjXbonCHN3VRADKE88Mq9wPS07YKqJzQ8D31GSUHFNYbmu5/WQXqB0LFg522JSJ3SWHvARWqsxrP3wpkDVcvrxtj3AvWgG+S0NZlsCCKsWrIq/M9nQg7UtF2tgJw3IEZtQuCKK6hSTSxuF3A=
  - secure: wQ2Y8LczmeqVeEtYuALedXvVzOlJ6yaZYrxsWNF62GPmgSECDQHRZ6/xotbHCkwthIZ7WFKi5D3AnF26cBdLD4is7QJCqVA/hplq4ymx9Qe3FCi8AZO63Lx17Sp1vUVEcanDpxxCwHHsPzHk6iO33z3+LgjFMSrYXbe8xAeYq7Q=
  - secure: "O5tejG6ql6L4rjLvVUgAA5sWoaOQ4cxoR0V1bh0E8PuR+uCj5otZ8y61+60mmZRVgSDFaZ7CNG1pUv2SJphxVlMr2zp5BxrCpEXFcY2yQ0YBMjIGb50KDv+F0DkqKAkogNd36AAuHDHVfsqGyiFYDnS0QaV7w2nYihtwq9PqEj0="
notifications: 
  recipients: 
  - akinsella@xebia.fr
