platform :ios, '6.0'

pod 'Reachability', 		 		'3.1.1'
pod 'SDWebImage',					'3.5.1'
pod 'MMDrawerController', 			'0.5.1'
pod 'Underscore.m',					'0.2.1'
pod 'ShareKit/Core',				'2.4.6'
pod 'ShareKit/Twitter',				'2.4.6'
pod	'ShareKit/ReadItLater',			'2.4.6'
pod 'AFNetworking',					'2.2.1'
pod 'MBProgressHUD',                '0.8'
pod 'SVPullToRefresh',				'0.4.1'
pod 'SDURLCache',					'1.2'
pod 'AFNetworkActivityLogger',		'2.0.1'
pod 'DCKeyValueObjectMapping', 		'1.4'
#pod 'PonyDebugger',				'0.0.1'
pod 'TTTAttributedLabel',			'1.7.5'
pod 'TestFlightSDK',                '2.1.3-beta'
pod 'SecureUDID',					'1.1'
pod 'DCIntrospect',					'0.0.2'
pod 'DTCoreText',					'1.6.10'
#pod 'DTFoundation',                 '1.6.1'
pod 'Appirater',					'2.0.2'
pod 'ZXingObjC',					'2.2.2'
pod 'NewRelicAgent',				'1.396'
pod 'InAppSettingsKit', 			'2.0'
pod 'ParseKit',						'0.7'
pod 'UIImageEffects', 				'~> 0.0'
pod 'DTMarkdownParser',				'0.2.1'
pod 'Reveal-iOS-SDK', 				'~> 1.0'
pod 'BlocksKit', 					'2.2'

target :"XebiaTests", :exclusive => true do
  pod 'SenTestingKitAsync',		'1.0.6'
#	pod 'GHUnitIOS',				'0.5.6'
	pod 'OCMock',					'2.2.1'
#	pod 'OCMockito',				'0.23'
#	pod 'Kiwi'
end
