platform :ios
pod 'JSONKit',      		 		'1.5pre'
pod 'LibComponentLogging-Core',		'1.2.2'
pod 'LibComponentLogging-NSLog',	'1.0.4'
pod 'Reachability', 		 		'3.0.0'
pod 'MBProgressHUD',				'0.5'
pod 'SDWebImage',					'2.6'
pod 'ZUUIRevealController',	 		'0.9.6'
pod 'RestKit',						'0.10.1'
pod 'Objection',					'0.13.0'
pod 'Underscore.m',					'0.1.0'
